### ISSUE TITLE
"Read More" link doesn't work

### ISSUE THREAD

**Issue by Mattsi-Jansky** [codurance/site#1036]
On: Careers page, toward the bottom of the page where there are several boxes with a picture, followed by a title followed by a "Read More" link.

What I expect to happen: I click the "Read More" link and get taken to the article

What happens: When I click the link, the address in the address bar changes but the page remains the same.

Reproduced in Chrome and Firefox. Clicking the image works but the text link doesn't.

**Comment by robertfirek** [comment]
There is an additional `#` in the links.
