### ISSUE TITLE
OGP embed image is too big

### ISSUE THREAD

**Issue by Mattsi-Jansky** [codurance/site#1038]
When we embed the OGP image (in this case using [Facebook's OGP Debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcodurance.com%2F)) it comes up as such: 

![image](https://user-images.githubusercontent.com/34603584/45304064-2a15aa80-b50f-11e8-97c3-aa75cb52ec7e.png)

See: https://opengraphcheck.com/result.php?url=https%3A%2F%2Fcodurance.com%2F

As you can see, it's too big and only a small part of cut-off text is appearing. I recommend changing ti . to `https://codurance.com/assets/custom/img/codurance-logo-artwork.png`, which is the smaller logo-only image we use for our Twitter-specific embed image. That comes out like so: 

![image](https://user-images.githubusercontent.com/34603584/45304189-74972700-b50f-11e8-8ee7-c7b452911edb.png)

**Comment by Mattsi-Jansky** [comment]
The Facebook OGP debugger is also warning us that we're returning a relative URL and should be returning an absolute URL. Perhaps LinkedIn isn't clever enough to resolve the relative URL to an absolute one?

**Comment by alfredodev** [comment]
Related tp #690

**Comment by sherlockq** [comment]
Spec ref:
https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en

**Comment by Mattsi-Jansky** [comment]
Looks much better in the Facebook and LinkedIn share debugger tools! Thanks everyone 👍
