### ISSUE TITLE
Remove sharethis

### ISSUE THREAD

**Issue by alfredodev** [codurance/site#1063]
It's adding a lot of cookies and from countries outside EU, see:
[Uploading report-codurancecom-1246176.pdf…]()

**Comment by Mattsi-Jansky** [comment]
I've played a bit with this in the past and couldn't see what it was actually adding to the site. Didn't seem to make any difference whether I blocked it or not, no new share widgets that I could see.

**Comment by alfredodev** [comment]
I think we can go for the simple share links of every platform and don't use any plugin
