### ISSUE TITLE
Create a docker image to run backstop in

### ISSUE THREAD

**Issue by chriseyre2000** [codurance/site#1131]
For those people who don't want to install backstopjs/node on their machines.

**Comment by MiyamotoAkira** [comment]
The `Dockerfile` file is the one used for development (it just uses the build image). Was left there specifically to add things that we want only to use at development time.

Probably the CMD and EXPOSE lines are not needed, as docker-compose will take care of it

**Comment by chriseyre2000** [comment]
There is a backstopjs/backstopjs image that allows backstop to be used without installing locally.
