### ISSUE TITLE
Outdated SC London 2018 banner

### ISSUE THREAD

**Issue by CarlosMChica** [codurance/site#1156]
I was reading a publication on our website yesterday and was hit with a banner about SC London 2018 which has already happened, we should probably remove this banner or change it for something more useful.

![screenshot_2018-11-01-13_49_24](https://user-images.githubusercontent.com/3494156/47855675-2f8bc480-dddd-11e8-963a-eb192dd7315f.png)

**Comment by Mattsi-Jansky** [comment]
Perhaps we should think of a way to avoid this happening in the future, too. Is there some way we could set up a notification/reminder to remove it? Wrapping it in a clause to only display until a certain date would be good too, but we'd still need to remember to come back and clean it up.

**Comment by alfredodev** [comment]
This is a starting point #1158 
We need to talk to @davidgrahamhall to see what more to do with this.
