### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by MiyamotoAkira** [codurance/site#1305]
I've just tried to use `docker-compose up` and I got this
```Starting site_site_1 ... done
Attaching to site_site_1
site_1  | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
site_1  | Bundler::GemfileNotFound: /usr/local/src/Gemfile not found```

**Comment by MiyamotoAkira** [comment]
This is a new clean system

**Comment by tonycodurance** [comment]
I cannot reproduce this issue. Is it ok to close @MiyamotoAkira?

**Comment by MiyamotoAkira** [comment]
I did a system prune and then rebuild and that seems to have done the trick. Maybe someone fixed it at some point
