### ISSUE TITLE
Review redirects

### ISSUE THREAD

**Issue by alfredodev** [codurance/site#1379]
For example, we have an aboutus folder with more subfolders just for the sake of adding redirects.

Review if these redirects are necessary or if there is another way of implementing it other than having folders and html files for this.

**Comment by sherlockq** [comment]
As per https://github.com/jekyll/jekyll-redirect-from it's possible to add `redirect-from` directives in the new page instead of keeping the old page. Sounds a good solution to me. I'll do some test with that see how it works.
@alfredodev
