### ISSUE TITLE
Have a proper ratio for the OGP image

### ISSUE THREAD

**Issue by sherlockq** [codurance/site#1627]
By default we provide https://codurance.es/assets/custom/img/codurance_open_graph.png as the OGP image for social sharing when paste a link from Codurance's website. It doesn't look perfect now.

![image](https://user-images.githubusercontent.com/615526/74959284-30959a80-5402-11ea-991f-bb8c6e67b1f4.png)

Relates to #690

**Comment by Mattsi-Jansky** [comment]
May be worth bringing up in the #design-requests channel in Codurance slack.

**Comment by sherlockq** [comment]
Find exactly same ticket. Sorry for duplication. #1038

**Comment by sherlockq** [comment]
Duplication
