### ISSUE TITLE
Help message for missing media due to cookies agreement

### ISSUE THREAD

**Issue by jfacchini** [codurance/site#1629]
# Problem statement

I just found out how to display the podcast player with the help of @MiyamotoAkira, I have to accept the cookies agreement.

I think that it would be useful to help any visitor that hadn't accepted yet the cookie, I found it quite difficult to understand why I couldn't see the player.

As a suggestion, maybe we could add a help message saying:
**"If you can't see the player below, you will need to accept to website cookies."**

# Step to reproduce

Open a browser using incognito mode or by delete the cookies from your current session and then navigate to one of the podcast page, for example: [https://codurance.com/podcasts/2019-12-02-serverless/](https://codurance.com/podcasts/2019-12-02-serverless/)

**Comment by Mattsi-Jansky** [comment]
Note from Jorge:

> Not on my computers now to reply on github. But this should be done on the template

**Comment by josewenzel** [comment]
I've figure it out, someone made a patch a while ago, cause apparently the message was being displayed at some point, this is the PR https://github.com/codurance/site/pull/1634

**Comment by jfacchini** [comment]
Thanks @jpwenzelc
