### ISSUE TITLE
Running linkchecker against the site has highlighted some 404s and typos

### ISSUE THREAD

**Issue by jordanrobinson** [codurance/site#1661]
After some discussion in slack, I've run [linkchecker](https://wummel.github.io/linkchecker/) against the site, and it had a few things that it complained about, output here:

[codurance-link-check.txt](https://github.com/codurance/site/files/4288169/codurance-link-check.txt)

(Note that while it says 403 I think that's before a redirect to 404 kicks in. The ones I manually checked all correctly displayed 404.)

This is likely related to #682 since this would have been flagged automatically if that was running against the build.

I think for this we need to first manually fix the issues, but then add a test to check that this doesn't happen again, likely fixing this one and #682.

**Comment by ghost** [comment]
I believe @chriseyre2000 wrote a link checker that's now [part of the build](https://github.com/codurance/site/blob/479cb353e5da6964fdd619f13d6695ee73c8f002/Rakefile#L74-L76)

**Comment by jordanrobinson** [comment]
We can probably close off this and also #682 in that case.
