### ISSUE TITLE
The Accept Cookies banner is appearing constantly

### ISSUE THREAD

**Issue by MiyamotoAkira** [codurance/site#1688]
Every time I go to a new page. Although I have installed both Privacy Badger and uBlock Origin,  this didn't use to happen. Pretty sure I have no such an issue when I published the latest podcast.

**Comment by keith-smale** [comment]
Can you screenshot the banner and add it here? 
Is it at the top of the page or the bottom?

**Comment by MiyamotoAkira** [comment]
![Codurance Cookie Banner](https://user-images.githubusercontent.com/3986689/79362226-3b6e3680-7f3e-11ea-8397-a91119dc8d83.png)

**Comment by MiyamotoAkira** [comment]
[Codurance Cookie Banner](https://user-images.githubusercontent.com/3986689/79362263-47f28f00-7f3e-11ea-9356-c6fa4c29e5a9.png)

**Comment by keith-smale** [comment]
That cookie banner is from HubSpot a 3rd party we are using in the site for embedded forms to capture/manage sales leads.
It was noticed that we didn't have the GDPR tools setup in HubSpot and I think this banner is a result of that.
We'll have a look into it.

**Comment by keith-smale** [comment]
I've made a tweak in the HubSpot settings so it should be gone now. I'll raise it on our daily this morning so we can decide if anything needs to be added to our cookie policy.
