### ISSUE TITLE
Mobile menu is too small for big greasy fingers

### ISSUE THREAD

**Issue by dhatanian** [codurance/site#291]
I tried accessing the nav menu from my mobile but most of the time I click on the wrong section. Would it make sense to have more space between each button?

**Comment by jukecraft** [comment]
@dhatanian is this still an issue with the new flat menu?

**Comment by dhatanian** [comment]
At normal zoom, yes it is near impossible to select the right option. When zooming though, it's working well. I'll close it as it feels like enough for now. Ideally on mobile the menu would display full screen.
