### ISSUE TITLE
HTTPS certificate error

### ISSUE THREAD

**Issue by jukecraft** [codurance/site#316]
when visiting https://codurance.com, a certificate error is shown:
<img width="843" alt="screen shot 2016-08-22 at 16 31 28" src="https://cloud.githubusercontent.com/assets/5154737/17860624/ea2c930c-6885-11e6-91a3-af27c4d38c58.png">

Unfortunately, GitHub Pages does not support HTTPS yet:
https://github.com/github/choosealicense.com/issues/299

**Comment by alvarogarcia7** [comment]
just to help diagnose, my blog works on https: https://alvarogarcia7.github.io

**Comment by dhatanian** [comment]
Closing as we've moved out of Github, and all the certificate-related issues on Amazon seem to be fixed.

I have tested:
- https://www.codurance.com
- https://www.codurance.es
- https://codurance.com
- https://codurance.es

And got no error message in Firefox, Chrome and Safari.
