### ISSUE TITLE
Email buttons on the careers page don't include the "mailto:" email address

### ISSUE THREAD

**Issue by sandromancuso** [codurance/site#391]

**Comment by jukecraft** [comment]
Seems like `site.email` is not defined https://github.com/codurance/site/search?utf8=%E2%9C%93&q=%22site.email%22&type=Code

**Comment by CarlosMChica** [comment]
I'll have a look at this first thing tomorrow morning.

**Comment by jukecraft** [comment]
@CarlosMChica please check https://github.com/codurance/site/pull/392 when you have a chance
