### ISSUE TITLE
Codurance logo overlaps menu in some circumstances

### ISSUE THREAD

**Issue by jukecraft** [codurance/site#405]
<img width="325" alt="screen shot 2016-10-04 at 16 30 01" src="https://cloud.githubusercontent.com/assets/5154737/19080746/f0250df2-8a4f-11e6-9e92-90488f9e533d.png">
Chrome Version 53.0.2785.116 (64-bit)
<img width="609" alt="screen shot 2016-10-04 at 16 31 49" src="https://cloud.githubusercontent.com/assets/5154737/19080776/1282fcba-8a50-11e6-8e79-4b3c4ad22ce8.png">

**Comment by jukecraft** [comment]
Same thing happens in Safari - probably because I increased the text size?
OS El Capitan 10.11.6

<img width="1010" alt="screen shot 2016-10-05 at 09 20 19" src="https://cloud.githubusercontent.com/assets/5154737/19106017/099eb21e-8add-11e6-8f1f-75d5d8002914.png">

**Comment by dhatanian** [comment]
No it also happens for screens under 1200px wide. I think this started
after the addition of the language selector.

**Comment by jukecraft** [comment]
@dhatanian I think this problem has been around a bit longer.... At least I remember it being around for a while and the language selector only got added recently

**Comment by jukecraft** [comment]
Solved, thanks @dhatanian 
![screen shot 2016-10-06 at 17 57 20](https://cloud.githubusercontent.com/assets/5154737/19162089/60db340a-8bee-11e6-9276-4fb200d7e673.png)
