### ISSUE TITLE
Missing redirection for /aboutus/ourteam/

### ISSUE THREAD

**Issue by dhatanian** [codurance/site#430]
Based on Google Analytics events added in #428 , the page `/aboutus/ourteam/` has been accessed twice by users coming from Google, which resulted in a 404. We need to add a redirection to `/company`.

![image](https://cloud.githubusercontent.com/assets/1684420/19420978/cbabe1a0-93ee-11e6-9ebd-a2fa5e8fa655.png)

**Comment by jukecraft** [comment]
doesn't seem to work yet
