### ISSUE TITLE
Old blog posts images are not shown

### ISSUE THREAD

**Issue by alvarogarcia7** [codurance/site#453]
See https://codurance.com/publications/page17/

<img width="870" alt="screen shot 2016-12-09 at 11 57 05" src="https://cloud.githubusercontent.com/assets/4199136/21048349/bf3658a0-be06-11e6-82ae-1379d5735d1a.png">

**Comment by CarlosMChica** [comment]
@alvarogarcia7 it's not that they are not shown. 

Posts without image just don't have an image set up in their config

**Comment by alvarogarcia7** [comment]
@CarlosMChica don't we have the default image, then?
