### ISSUE TITLE
Client logos look weird on mobile browser

### ISSUE THREAD

**Issue by jukecraft** [codurance/site#460]
The clients website viewed in Chrome on Android has huge Logos that look crowded and squashed together. The partnership with Jetbrains note is tiny in comparison.

![screenshot_20161213-133621](https://cloud.githubusercontent.com/assets/5154737/21144406/66b2e358-c142-11e6-9ba3-4340b5c1bcdc.png)
![screenshot_20161213-133628](https://cloud.githubusercontent.com/assets/5154737/21144404/66b1efc0-c142-11e6-8c93-6e3c20bbda9c.png)
![screenshot_20161213-133633](https://cloud.githubusercontent.com/assets/5154737/21144407/66b7cf58-c142-11e6-8174-e658010f2bae.png)
![screenshot_20161213-133741](https://cloud.githubusercontent.com/assets/5154737/21144405/66b28e26-c142-11e6-84fe-8f209e5a37f8.png)

**Comment by CarlosMChica** [comment]
@franziskas I just checked, and it looks ok, could you please confirm and close the issue?. I think the issue was that the client's section was not correctly shown in general, not just for mobile devices

**Comment by jukecraft** [comment]
@CarlosMChica looks better now
