### ISSUE TITLE
Images inside blog posts are sometimes too big

### ISSUE THREAD

**Issue by ghost** [codurance/site#495]
see example:
https://codurance.com/2015/03/16/installing-zprezto-a-quick-guide/

**Comment by ghost** [comment]
One solution is to set image attributes to `width: 100%;`
But I have to check it does not affect other stuff on the website

**Comment by cyplo** [comment]
Would it affect a fix for #500 ?

**Comment by ghost** [comment]
No it does not unfortunately.

**Comment by lpalma** [comment]
Closing as this issue is treated as fixed by #505
