### ISSUE TITLE
Dead links found on Codurance.com

### ISSUE THREAD

**Issue by neomatrix369** [codurance/site#503]
I ran a scan using Deadlinkschecker.com and found a number of dead links:
https://docs.google.com/document/d/1SDNZlK2Yqrl2t0KZHTWCrx3aL47G2XsJ7pOtyIuquzY/edit#heading=h.dc0sbol9xwk7

Most might be trivial to fix, some important ones others might be a good-to-fix.

A number of these are sprouting from the .css files we have being using.

**Comment by neomatrix369** [comment]
Not every one of these are a quick-win and its good to fix many of these broken links, it's important we refer to the correct target.

A good idea is to create smaller issues from the big list and solve them separately and refer to this issue from each of them.

**Comment by neomatrix369** [comment]
Spoke to @TobyRet and @tekavec about this pending issue - fixing CSS that refer to unavailable resources or unused CSS references. The general idea is its good to have a clean CSS file and references but it is okay not to invest any more time on trying to fix it.

So this is up for discussions, happy fix the CSS issues and then close this or close this issue if CSS issues are something we can live with.

There are some other non-CSS related issues as well in this Google Doc - some are unresolvable, others might need to be discussed.

**Comment by neomatrix369** [comment]
Re-ran the Dead links checker on codurance.com and the results are `100% scanned - 2000/2000 URLs checked, 1966 OK, 34 failed`, down from 56 failures. And most of these failures are CSS issues which we are waiting a verdict on.

**Comment by cyplo** [comment]
With both references pull requests closed - what is the situation now ?

**Comment by neomatrix369** [comment]
@cyplo See https://github.com/codurance/site/issues/503#issuecomment-271598395 - pending

**Comment by neomatrix369** [comment]
Closing this issue.

Will not fix:
- CSS issues related to the `styles.css` files 
- other dead / irrecoverable third-party external links
- will create a separate issue for these broken links:
  - https://msdn.microsoft.com/en-us/library/ms254498v=vs.110.aspx
(CLR integration) in https://codurance.com/2016/10/06/database-testing-with-tsqlt/
  - https://www.microsoft.com/en-us/download/details.aspx?id=52679 (SQL Server Express) in
https://codurance.com/2016/10/06/database-testing-with-tsqlt/
