### ISSUE TITLE
[Chrome only] Layout differences in page when switching between EN and ES on any page on the site

### ISSUE THREAD

**Issue by neomatrix369** [codurance/site#506]
In Chrome, clicking on the EN and ES links shows pages in these layouts:

_**EN active**, ES inactive_
![screen shot 2017-01-09 at 16 36 41](https://cloud.githubusercontent.com/assets/1570917/21774296/f31ded40-d689-11e6-88fc-61b81684efeb.png)

_EN inactive, **ES active**_
![screen shot 2017-01-09 at 16 36 57](https://cloud.githubusercontent.com/assets/1570917/21774355/18cb181a-d68a-11e6-86df-cf2088829b00.png)

The text on the top panel is a bit smaller and the image is pulled a bit higher when **ES active**.

_This is not an issue in Firefox or Safari._

**Comment by robertfirek** [comment]
Cannot be reproduced. In my Chrome version, it is not visible. Probably fixed by another change.
