### ISSUE TITLE
Apply https to URLs in blog posts wherever https is available

### ISSUE THREAD

**Issue by neomatrix369** [codurance/site#513]
After discussion with @cyplo, we decided to replace all `http` protocols on URLs referred to in the blog posts and elsewhere on the site to `https`, wherever this is available.

Some work has already been done via #508, the rest will be done via this separate issue.

**Comment by lpalma** [comment]
@cyplo is this issue still relevant?

**Comment by MiyamotoAkira** [comment]
Whole site is now https
