### ISSUE TITLE
Get external checks going for robots

### ISSUE THREAD

**Issue by cyplo** [codurance/site#518]
Check periodically if the site can be accessed by robots correctly.
Bonus points for checking for each pull request before merging.
See #516, #418

**Comment by sjn88** [comment]
We use google webmaster tools for this, but did you have something else in mind?

**Comment by lpalma** [comment]
@cyplo is this issue still relevant?

**Comment by Mattsi-Jansky** [comment]
Appears to be no longer relevant so I'm going to close, feel free to re-open if I'm mistaken.
