### ISSUE TITLE
Migrate Jenkins configuration to be stored in the repo fully

### ISSUE THREAD

**Issue by cyplo** [codurance/site#519]
There are some pieces of the configuration, e.g. which scripts to launch and in which order, stored in Jenkins itself. If there are changes done to this configuration it will affect all branches. It would be good imho to have this done per-branch, which new Jenkins can do I believe. Previously it was done by the Pipeline and SCM Sync plugins, I think this is now a part of Jenkins proper.

**Comment by neomatrix369** [comment]
Version control configuration - way to `Infrastructure as code` :)

**Comment by PaNaVTEC** [comment]
This is already done: https://github.com/codurance/site/pull/527
