### ISSUE TITLE
Thanks page is not translated to spanish

### ISSUE THREAD

**Issue by PaNaVTEC** [codurance/site#521]

**Comment by jukecraft** [comment]
@PaNaVTEC if you add the issue number `#521` in a commit message, this will automatically close when the commit is merged.

**Comment by PaNaVTEC** [comment]
Thanks for tip @franziskas I didn't know that was a feature of github 👍

**Comment by PaNaVTEC** [comment]
Finally I didn't have the chance to commit again, closed because https://github.com/codurance/site/pull/537 fixes this
