### ISSUE TITLE
Some html test

### ISSUE THREAD

**Issue by PaNaVTEC** [codurance/site#534]
There is a tool to validate html output: https://github.com/gjtorikian/html-proofer maybe is worth take a look. CircleCI is using it in its documentation repo: https://github.com/circleci/circleci-docs/blob/master/circle.yml

**Comment by neomatrix369** [comment]
Let's give it a whirl and see where it gets us!

**Comment by chriseyre2000** [comment]
Did give it a whirl. It gives vague errors.

**Comment by sherlockq** [comment]
Stale.
