### ISSUE TITLE
Failure to send a comment fails the build

### ISSUE THREAD

**Issue by cyplo** [codurance/site#546]
As in a build for  #542 

would it be okay to allow failures in this section of the build ? what do you think ?

**Comment by jukecraft** [comment]
Workaround: click "rebuild" in circle CI

**Comment by jukecraft** [comment]
@cyplo can we retry? Happy to allow failures in this part though.

**Comment by cyplo** [comment]
Let me see if I understood correctly:

The algorithm to be:
* retry N times if failed if possible ?
* fail the build if N failures
 
 ?

**Comment by jukecraft** [comment]
I meant
- retry N times the step that posts the comment if failed
- do not fail the build if commenting fails

but I'm happy with either
