### ISSUE TITLE
Newsletter subscription button not styled

### ISSUE THREAD

**Issue by cyplo** [codurance/site#656]
Hello !
Signing in to the newsletter, I see unstyled `Subscribe` button.
I'm using Firefox 53 with uBlock, uBlock seems to be blocking just google analytics though.

![screenshot from 2017-05-13 06-15-19](https://cloud.githubusercontent.com/assets/217899/26022726/1d124634-37a4-11e7-896e-55014e86274c.png)

**Comment by lpalma** [comment]
@cyplo I can't find the newsletter form in our page. Do we still have it? If not, I believe we can close this Issue

**Comment by lpalma** [comment]
>... I can't find the newsletter form in our page. Do we still have it? If not, I believe we can close this Issue

Closing as it is no longer available in the current version of the website
