### ISSUE TITLE
URL is pulling images from site by date order

### ISSUE THREAD

**Issue by davidgrahamhall** [codurance/site#690]
When pasting URL of Codurnace.com or Codurance.com/xxx, the image being pulled appears to be the last image that was uploaded to the site, as opposed to the Company logo. This is most notable on social media sites such as LinkedIn or Twitter.

<img width="536" alt="codurance3" src="https://user-images.githubusercontent.com/23401754/27483964-5e0bc282-581f-11e7-95f9-bee14cb2bf49.png">

**Comment by robertfirek** [comment]
Probably it is problem with the parser for Open Graph Protocol in Linkedin. I found some pages where people describe problems with the OGP in Linkedin. 
I've made some changes. Unfortunately, they also cache all results for 7 days, so we have to wait until the invalidation will be triggered by Linkedin. They don't provide the possibility to do it manually.

**Comment by Mattsi-Jansky** [comment]
Looks like this issue is still affecting us. Any more ideas @robertfirek ?
![image](https://user-images.githubusercontent.com/34603584/45303924-d86d2000-b50e-11e8-9ed8-4222aea6395a.png)

**Comment by Mattsi-Jansky** [comment]
This might relate to my comment on #1038

**Comment by alfredodev** [comment]
Maybe is because we are not fulfilling the image requeriments:

> Here are the image requirements specific to the LinkedIn sharing module:
> 
> Max file size: 5 MB
> Minimum image dimensions: 1200 (w) x 627 (h) pixels
> Recommended ratio: 1.91:1
From: https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en

Wich colides with the facebook recomandation on #1038

**Comment by alfredodev** [comment]
We can try with this:
http://ogp.me/#array
https://stackoverflow.com/questions/8365156/how-to-set-priority-order-to-open-graph-images-for-links-that-are-inserted-in-co/12726245#12726245

**Comment by sherlockq** [comment]
Not perfect. Need a second opinion on this issue.
![image](https://user-images.githubusercontent.com/615526/74958615-21621d00-5401-11ea-87fd-7862bb7c2e33.png)

**Comment by sherlockq** [comment]
We already have OGP implemented but the image is not in perfect ratio. I'll create another ticket covering this issue.

https://codurance.es/assets/custom/img/codurance_open_graph.png
