### ISSUE TITLE
Lost page in /publications

### ISSUE THREAD

**Issue by cyplo** [codurance/site#777]
Right now (02/11/2017) this post https://codurance.com/2017/08/21/a-reflection-on-software-craftsmanship/ should be on the second page of /publications. It is nowhere to be seen as other posts from September to January. The post is accessible if you know the URL/googled for it - but you cannot browse through the page to find it.

**Comment by cyplo** [comment]
Props to @rachelcarmena for finding this

**Comment by cyplo** [comment]
I think we've traced the issue with @cohen990 .
Some time in January/February something about the build system has changed.
We were using directories for `/publications/pageX/index.html` where X is the number of the page.
Now the build system generates `/publications/pageX.html` instead.
The sync mechanism does not delete old files when uploading.

All of the above combined means that we are generating a proper version of page2 but it's not being linked to from the main page. What is being linked to is the index.html in the page2 folder, which contains stale data from February, which hasn't been cleaned up by the build.

- [x] Either make the build system link to `.html` address instead of just the folder or go back to generating the folder structure instead of just html page
- [ ] Make sure that the upload mechanism syncs the contents strictly
- [ ] Set up a smoke test/monitoring to get alerted when similar things happen in the future

**Comment by rachelcarmena** [comment]
Congrats @cyplo , @cohen990 !!
