### ISSUE TITLE
Metadata has "Craftsmen" - should have "Craftspeople"

### ISSUE THREAD

**Issue by cohen990** [codurance/site#824]
<img width="678" alt="screen shot 2017-12-06 at 14 54 18" src="https://user-images.githubusercontent.com/4104871/33671079-8dd2e35e-da9e-11e7-990d-eadaffddc803.png">

We want to replace this metadata in google search with 

"Our team of dedicated software craftspeople provides consultancy, software development, and training services to clients seeking high quality development processes and software solutions."

**Comment by mashooq** [comment]
Fixed in latest pull request.
