### ISSUE TITLE
List of articles written beneath employee details

### ISSUE THREAD

**Issue by cohen990** [codurance/site#832]
What we offer as a company is expertise and each individual has their own area of expertise. We should capitalise on this and emphasise the expertise by listing each employees blog posts beneath their picture on the company page.

<img width="441" alt="mockup" src="https://user-images.githubusercontent.com/4104871/33882128-0af2d1fc-df2f-11e7-9fa1-bfbb6311b996.png">

obviously I'm bad at layouts and font matching - but that's the general idea

**Comment by keith-smale** [comment]
It would be good to let a visitor see the posts that someone has added. If it were someone like Sandro though the list would be quite long.

What if there was a link under each user which took you to the authored blogs page for that user (https://codurance.com/publications/author/dan-cohen/) ?

**Comment by cohen990** [comment]
Could also limit it to three or so and provide a link to the rest of them

Even just having the link would help for discoverability - I never realised that we had an authored blogs page

**Comment by keith-smale** [comment]
Made some changes and added a link to the author page. See this pull request #923 .

Let me know what you think.

**Comment by MiyamotoAkira** [comment]
The pull request was merged
